package com.coolweather.app.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

/**
 * Created by lenovo on 2015/7/10.
 */
public class CoolWeatherOpenHelper extends SQLiteOpenHelper {

    public static final String CREATE_PROVINCE = "create table Province (" +
            "id integer primary key , " +
            "province_name text, " +
            "province_code text)";

    public static final String CREATE_CITY = "create table City (" +
            "id integer primary key , " +
            "city_name text, " +
            "city_code text, " +
            "province_id integer)";

    public static final String CREATE_COUNTY = "create table County (" +
            "id integer primary key , " +
            "county_name text, " +
            "county_code text, " +
            "city_id integer)";

    public CoolWeatherOpenHelper(Context context, String name, SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL(CREATE_PROVINCE);
        db.execSQL(CREATE_CITY);
        db.execSQL(CREATE_COUNTY);

        db.execSQL("insert into Province values (?,?,?)",new String[] {"01","北京","01"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"02", "上海", "02"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"03","天津","03"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"04","重庆","04"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"05","黑龙江","05"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"06","吉林","06"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"07","辽宁","07"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"08","内蒙古","08"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"09","河北","09"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"10","山西","10"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"11","陕西","11"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"12","山东","12"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"13","新疆","13"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"14","西藏","14"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"15","青海","15"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"16","甘肃","16"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"17","宁夏","17"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"18","河南","18"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"19","江苏","19"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"20","湖北","20"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"21","浙江","21"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"22","安徽","22"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"23","福建","23"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"24","江西","24"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"25","湖南","25"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"26","贵州","26"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"27","四川","27"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"28","广东","28"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"29","云南","29"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"30","广西","30"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"31","海南","31"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"32","香港","32"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"33","澳门","33"});
        db.execSQL("insert into Province values (?,?,?)",new String[] {"34","台湾","34"});

        db.execSQL("insert into City values (?,?,?,?)",new String[] {"1","北京","0101","01"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"2","上海","0201","02"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"3","天津","0301","03"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"4","重庆","0401","04"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"5","哈尔滨","0501","05"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"6","齐齐哈尔","0502","05"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"7","牡丹江","0503","05"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"8","佳木斯","0504","05"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"9","绥化","0505","05"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"10","黑河","0506","05"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"11","大兴安岭","0507","05"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"12","伊春","0508","05"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"13","大庆","0509","05"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"14","七台河","0510","05"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"15","鸡西","0511","05"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"16","鹤岗","0512","05"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"17","双鸭山","0513","05"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"18","长春","0601","06"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"19","吉林","0602","06"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"20","延边","0603","06"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"21","四平","0604","06"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"22","通化","0605","06"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"23","白城","0606","06"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"24","辽源","0607","06"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"25","松原","0608","06"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"26","白山","0609","06"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"27","沈阳","0701","07"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"28","大连","0702","07"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"29","鞍山","0703","07"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"30","抚顺","0704","07"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"31","本溪","0705","07"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"32","丹东","0706","07"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"33","锦州","0707","07"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"34","营口","0708","07"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"35","阜新","0709","07"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"36","辽阳","0710","07"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"37","铁岭","0711","07"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"38","朝阳","0712","07"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"39","盘锦","0713","07"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"40","葫芦岛","0714","07"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"41","呼和浩特","0801","08"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"42","包头","0802","08"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"43","乌海","0803","08"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"44","乌兰察布","0804","08"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"45","通辽","0805","08"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"46","赤峰","0806","08"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"47","鄂尔多斯","0807","08"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"48","巴彦淖尔","0808","08"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"49","锡林郭勒","0809","08"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"50","呼伦贝尔","0810","08"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"51","兴安盟","0811","08"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"52","阿拉善盟","0812","08"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	53	","	石家庄	","	901	","	9	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	54	","	保定	","	902	","	9	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	55	","	张家口	","	903	","	9	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	56	","	承德	","	904	","	9	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	57	","	唐山	","	905	","	9	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	58	","	廊坊	","	906	","	9	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	59	","	沧州	","	907	","	9	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	60	","	衡水	","	908	","	9	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	61	","	邢台	","	909	","	9	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	62	","	邯郸	","	910	","	9	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	63	","	秦皇岛	","	911	","	9	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	64	","	太原	","	1001	","	10	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	65	","	大同	","	1002	","	10	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	66	","	阳泉	","	1003	","	10	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	67	","	晋中	","	1004	","	10	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	68	","	长治	","	1005	","	10	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	69	","	晋城	","	1006	","	10	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	70	","	临汾	","	1007	","	10	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	71	","	运城	","	1008	","	10	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	72	","	朔州	","	1009	","	10	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	73	","	忻州	","	1010	","	10	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	74	","	吕梁	","	1011	","	10	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	75	","	西安	","	1101	","	11	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	76	","	咸阳	","	1102	","	11	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	77	","	延安	","	1103	","	11	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	78	","	榆林	","	1104	","	11	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	79	","	渭南	","	1105	","	11	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	80	","	商洛	","	1106	","	11	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	81	","	安康	","	1107	","	11	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	82	","	汉中	","	1108	","	11	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	83	","	宝鸡	","	1109	","	11	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	84	","	铜川	","	1110	","	11	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	85	","	杨凌	","	1111	","	11	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	86	","	济南	","	1201	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	87	","	青岛	","	1202	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	88	","	淄博	","	1203	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	89	","	德州	","	1204	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	90	","	烟台	","	1205	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	91	","	潍坊	","	1206	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	92	","	济宁	","	1207	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	93	","	泰安	","	1208	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	94	","	临沂	","	1209	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	95	","	菏泽	","	1210	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	96	","	滨州	","	1211	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	97	","	东营	","	1212	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	98	","	威海	","	1213	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	99	","	枣庄	","	1214	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	100	","	日照	","	1215	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	101	","	莱芜	","	1216	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	102	","	聊城	","	1217	","	12	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	103	","	乌鲁木齐	","	1301	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	104	","	克拉玛依	","	1302	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	105	","	石河子	","	1303	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	106	","	昌吉	","	1304	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	107	","	吐鲁番	","	1305	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	108	","	巴音郭楞	","	1306	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	109	","	阿拉尔	","	1307	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	110	","	阿克苏	","	1308	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	111	","	喀什	","	1309	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	112	","	伊犁	","	1310	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	113	","	塔城	","	1311	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	114	","	哈密	","	1312	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	115	","	和田	","	1313	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	116	","	阿勒泰	","	1314	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	117	","	克州	","	1315	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	118	","	博尔塔拉	","	1316	","	13	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	119	","	拉萨	","	1401	","	14	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	120	","	日喀则	","	1402	","	14	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	121	","	山南	","	1403	","	14	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	122	","	林芝	","	1404	","	14	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	123	","	昌都	","	1405	","	14	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	124	","	那曲	","	1406	","	14	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	125	","	阿里	","	1407	","	14	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	126	","	西宁	","	1501	","	15	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	127	","	海东	","	1502	","	15	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	128	","	黄南	","	1503	","	15	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	129	","	海南	","	1504	","	15	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	130	","	果洛	","	1505	","	15	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	131	","	玉树	","	1506	","	15	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	132	","	海西	","	1507	","	15	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	133	","	海北	","	1508	","	15	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	134	","	格尔木	","	1509	","	15	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	135	","	兰州	","	1601	","	16	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	136	","	定西	","	1602	","	16	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	137	","	平凉	","	1603	","	16	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	138	","	庆阳	","	1604	","	16	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	139	","	武威	","	1605	","	16	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	140	","	金昌	","	1606	","	16	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	141	","	张掖	","	1607	","	16	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	142	","	酒泉	","	1608	","	16	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	143	","	天水	","	1609	","	16	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	144	","	陇南	","	1610	","	16	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	145	","	临夏	","	1611	","	16	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	146	","	甘南	","	1612	","	16	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	147	","	白银	","	1613	","	16	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	148	","	嘉峪关	","	1614	","	16	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	149	","	银川	","	1701	","	17	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	150	","	石嘴山	","	1702	","	17	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	151	","	吴忠	","	1703	","	17	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	152	","	固原	","	1704	","	17	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	153	","	中卫	","	1705	","	17	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	154	","	郑州	","	1801	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	155	","	安阳	","	1802	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	156	","	新乡	","	1803	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	157	","	许昌	","	1804	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	158	","	平顶山	","	1805	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	159	","	信阳	","	1806	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	160	","	南阳	","	1807	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	161	","	开封	","	1808	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	162	","	洛阳	","	1809	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	163	","	商丘	","	1810	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	164	","	焦作	","	1811	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	165	","	鹤壁	","	1812	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	166	","	濮阳	","	1813	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	167	","	周口	","	1814	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	168	","	漯河	","	1815	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	169	","	驻马店	","	1816	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	170	","	三门峡	","	1817	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	171	","	济源	","	1818	","	18	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	172	","	南京	","	1901	","	19	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	173	","	无锡	","	1902	","	19	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	174	","	镇江	","	1903	","	19	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	175	","	苏州	","	1904	","	19	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	176	","	南通	","	1905	","	19	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	177	","	扬州	","	1906	","	19	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	178	","	盐城	","	1907	","	19	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	179	","	徐州	","	1908	","	19	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	180	","	淮安	","	1909	","	19	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	181	","	连云港	","	1910	","	19	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	182	","	常州	","	1911	","	19	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	183	","	泰州	","	1912	","	19	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	184	","	宿迁	","	1913	","	19	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	185	","	武汉	","	2001	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	186	","	襄阳	","	2002	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	187	","	鄂州	","	2003	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	188	","	孝感	","	2004	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	189	","	黄冈	","	2005	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	190	","	黄石	","	2006	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	191	","	咸宁	","	2007	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	192	","	荆州	","	2008	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	193	","	宜昌	","	2009	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	194	","	恩施	","	2010	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	195	","	十堰	","	2011	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	196	","	神农架	","	2012	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	197	","	随州	","	2013	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	198	","	荆门	","	2014	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	199	","	天门	","	2015	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	200	","	仙桃	","	2016	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	201	","	潜江	","	2017	","	20	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	202	","	杭州	","	2101	","	21	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	203	","	湖州	","	2102	","	21	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	204	","	嘉兴	","	2103	","	21	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	205	","	宁波	","	2104	","	21	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	206	","	绍兴	","	2105	","	21	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	207	","	台州	","	2106	","	21	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	208	","	温州	","	2107	","	21	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	209	","	丽水	","	2108	","	21	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	210	","	金华	","	2109	","	21	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	211	","	衢州	","	2110	","	21	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	212	","	舟山	","	2111	","	21	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	213	","	合肥	","	2201	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	214	","	蚌埠	","	2202	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	215	","	芜湖	","	2203	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	216	","	淮南	","	2204	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	217	","	马鞍山	","	2205	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	218	","	安庆	","	2206	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	219	","	宿州	","	2207	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	220	","	阜阳	","	2208	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	221	","	亳州	","	2209	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	222	","	黄山	","	2210	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	223	","	滁州	","	2211	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	224	","	淮北	","	2212	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	225	","	铜陵	","	2213	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	226	","	宣城	","	2214	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	227	","	六安	","	2215	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	228	","	池州	","	2217	","	22	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	229	","	福州	","	2301	","	23	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	230	","	厦门	","	2302	","	23	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	231	","	宁德	","	2303	","	23	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	232	","	莆田	","	2304	","	23	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	233	","	泉州	","	2305	","	23	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	234	","	漳州	","	2306	","	23	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	235	","	龙岩	","	2307	","	23	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	236	","	三明	","	2308	","	23	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	237	","	南平	","	2309	","	23	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	238	","	南昌	","	2401	","	24	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	239	","	九江	","	2402	","	24	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	240	","	上饶	","	2403	","	24	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	241	","	抚州	","	2404	","	24	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	242	","	宜春	","	2405	","	24	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	243	","	吉安	","	2406	","	24	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	244	","	赣州	","	2407	","	24	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	245	","	景德镇	","	2408	","	24	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	246	","	萍乡	","	2409	","	24	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	247	","	新余	","	2410	","	24	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	248	","	鹰潭	","	2411	","	24	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	249	","	长沙	","	2501	","	25	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	250	","	湘潭	","	2502	","	25	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	251	","	株洲	","	2503	","	25	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	252	","	衡阳	","	2504	","	25	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	253	","	郴州	","	2505	","	25	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	254	","	常德	","	2506	","	25	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	255	","	益阳	","	2507	","	25	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	256	","	娄底	","	2508	","	25	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	257	","	邵阳	","	2509	","	25	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	258	","	岳阳	","	2510	","	25	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	259	","	张家界	","	2511	","	25	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	260	","	怀化	","	2512	","	25	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	261	","	永州	","	2514	","	25	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	262	","	湘西	","	2515	","	25	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	263	","	贵阳	","	2601	","	26	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	264	","	遵义	","	2602	","	26	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	265	","	安顺	","	2603	","	26	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	266	","	黔南	","	2604	","	26	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	267	","	黔东南	","	2605	","	26	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	268	","	铜仁	","	2606	","	26	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	269	","	毕节	","	2607	","	26	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	270	","	六盘水	","	2608	","	26	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	271	","	黔西南	","	2609	","	26	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	272	","	成都	","	2701	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	273	","	攀枝花	","	2702	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	274	","	自贡	","	2703	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	275	","	绵阳	","	2704	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	276	","	南充	","	2705	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	277	","	达州	","	2706	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	278	","	遂宁	","	2707	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	279	","	广安	","	2708	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	280	","	巴中	","	2709	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	281	","	泸州	","	2710	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	282	","	宜宾	","	2711	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	283	","	内江	","	2712	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	284	","	资阳	","	2713	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	285	","	乐山	","	2714	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	286	","	眉山	","	2715	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	287	","	凉山	","	2716	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	288	","	雅安	","	2717	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	289	","	甘孜	","	2718	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	290	","	阿坝	","	2719	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	291	","	德阳	","	2720	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	292	","	广元	","	2721	","	27	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	293	","	广州	","	2801	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	294	","	韶关	","	2802	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	295	","	惠州	","	2803	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	296	","	梅州	","	2804	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	297	","	汕头	","	2805	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	298	","	深圳	","	2806	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	299	","	珠海	","	2807	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	300	","	佛山	","	2808	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	301	","	肇庆	","	2809	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	302	","	湛江	","	2810	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	303	","	江门	","	2811	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	304	","	河源	","	2812	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	305	","	清远	","	2813	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	306	","	云浮	","	2814	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	307	","	潮州	","	2815	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	308	","	东莞	","	2816	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	309	","	中山	","	2817	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	310	","	阳江	","	2818	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	311	","	揭阳	","	2819	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	312	","	茂名	","	2820	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	313	","	汕尾	","	2821	","	28	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	314	","	昆明	","	2901	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	315	","	大理	","	2902	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	316	","	红河	","	2903	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	317	","	曲靖	","	2904	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	318	","	保山	","	2905	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	319	","	文山	","	2906	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	320	","	玉溪	","	2907	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	321	","	楚雄	","	2908	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	322	","	普洱	","	2909	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	323	","	昭通	","	2910	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	324	","	临沧	","	2911	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	325	","	怒江	","	2912	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	326	","	迪庆	","	2913	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	327	","	丽江	","	2914	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	328	","	德宏	","	2915	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	329	","	西双版纳	","	2916	","	29	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	330	","	南宁	","	3001	","	30	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	331	","	崇左	","	3002	","	30	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	332	","	柳州	","	3003	","	30	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	333	","	来宾	","	3004	","	30	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	334	","	桂林	","	3005	","	30	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	335	","	梧州	","	3006	","	30	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	336	","	贺州	","	3007	","	30	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	337	","	贵港	","	3008	","	30	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	338	","	玉林	","	3009	","	30	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	339	","	百色	","	3010	","	30	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	340	","	钦州	","	3011	","	30	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	341	","	河池	","	3012	","	30	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	342	","	北海	","	3013	","	30	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	343	","	防城港	","	3014	","	30	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	344	","	海口	","	3101	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	345	","	三亚	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	346	","	东方	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	347	","	临高	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	348	","	澄迈	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	349	","	儋州	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	350	","	昌江	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	351	","	白沙	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	352	","	琼中	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	353	","	定安	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	354	","	屯昌	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	355	","	琼海	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	356	","	文昌	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	357	","	保亭	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	358	","	万宁	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	359	","	陵水	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	360	","	西沙	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	361	","	南沙	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	362	","	乐东	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	363	","	五指山	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	364	","	中沙	","	3102	","	31	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	365	","	香港	","	3201	","	32	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	366	","	澳门	","	3301	","	33	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	367	","	台北	","	3401	","	34	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	368	","	高雄	","	3402	","	34	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	369	","	台中	","	3404	","	34	"});
        db.execSQL("insert into City values (?,?,?,?)",new String[] {"	370	","	南子岛	","	3102	","	31	"});


        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	1	","	北京	","010100","	1	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	2	","	海淀	","010200","	1	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	3	","	朝阳	","010300","	1	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	4	","	顺义	","010400","	1	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	5	","	怀柔	","	010500	","	1	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	6	","	通州	","	010600	","	1	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	7	","	昌平	","	010700	","	1	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	8	","	延庆	","	010800	","	1	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	9	","	丰台	","	010900	","	1	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	10	","	石景山	","	011000	","	1	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	11	","	大兴	","	011100	","	1	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	12	","	房山	","	011200	","	1	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	13	","	密云	","	011300	","	1	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	14	","	门头沟	","	011400	","	1	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	15	","	平谷	","	011500	","	1	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	16	","	上海	","	020100	","	2	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	17	","	闵行	","	020200	","	2	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	18	","	宝山	","	020300	","	2	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	19	","	嘉定	","	020500	","	2	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	20	","	浦东新区	","	020600	","	2	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	21	","	金山	","	020700	","	2	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	22	","	青浦	","020800	","	2	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	23	","	松江	","	020900	","	2	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	24	","	奉贤	","	021000	","	2	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	25	","	崇明	","	021100	","	2	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	26	","	徐汇	","	021200	","	2	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	27	","	天津	","	030100	","	3	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	28	","	武清	","	030200	","	3	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	29	","	宝坻	","	030300	","	3	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	30	","	东丽	","	030400	","	3	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	31	","	西青	","	030500	","	3	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	32	","	北辰	","	030600	","	3	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	33	","	宁河	","	030700	","	3	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	34	","	静海	","	030900	","	3	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	35	","	津南	","	031000	","	3	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	36	","	滨海新区	","	031100	","	3	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	37	","	蓟县	","	031400	","	3	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	38	","	重庆	","	040100	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	39	","	永川	","	040200	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	40	","	合川	","	040300	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	41	","	南川	","	040400	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	42	","	江津	","	040500	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	43	","	万盛	","	040600	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	44	","	渝北	","	040700	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	45	","	北碚	","	040800	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	46	","	巴南	","	040900	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	47	","	长寿	","	041000	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	48	","	黔江	","	041100	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	49	","	万州	","	041300	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	50	","	涪陵	","	041400	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	51	","	开县	","	041500	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	52	","	城口	","	041600	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	53	","	云阳	","	041700	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	54	","	巫溪	","	041800	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	55	","	奉节	","	041900	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	56	","	巫山	","	042000	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	57	","	潼南	","	042100	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	58	","	垫江	","	042200	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	59	","	梁平	","	042300	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	60	","	忠县	","	042400	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	61	","	石柱	","	042500	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	62	","	大足	","	042600	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	63	","	荣昌	","	042700	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	64	","	铜梁	","	042800	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	65	","	璧山	","	042900	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	66	","	丰都	","	043000	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	67	","	武隆	","	043100	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	68	","	彭水	","	043200	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	69	","	綦江	","	043300	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	70	","	酉阳	","	043400	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	71	","	秀山	","	043600	","	4	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	72	","	哈尔滨	","	050101	","	5	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	73	","	双城	","	050102	","	5	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	74	","	呼兰	","	050103	","	5	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	75	","	阿城	","	050104	","	5	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	76	","	宾县	","	050105	","	5	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	77	","	依兰	","	050106	","	5	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	78	","	巴彦	","	050107	","	5	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	79	","	通河	","	050108	","	5	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	80	","	方正	","	050109	","	5	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	81	","	延寿	","	050110	","	5	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	82	","	尚志	","	050111	","	5	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	83	","	五常	","	050112	","	5	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	84	","	木兰	","	050113	","	5	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	85	","	齐齐哈尔	","	050201	","	6	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	86	","	讷河	","	050202	","	6	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	87	","	龙江	","	050203	","	6	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	88	","	甘南	","	050204	","	6	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	89	","	富裕	","050205	","	6	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	90	","	依安	","	050206	","	6	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	91	","	拜泉	","	050207	","	6	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	92	","	克山	","	050208	","	6	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	93	","	克东	","050209	","	6	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	94	","	泰来	","	050210	","	6	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	95	","	牡丹江	","	050301	","	7	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	96	","	海林	","	050302	","	7	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	97	","	穆棱	","	050303	","	7	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	98	","	林口	","	050304	","	7	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	99	","	绥芬河	","	050305	","	7	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	100	","	宁安	","	050306	","	7	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	101	","	东宁	","	050307	","	7	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	102	","	佳木斯	","	050401	","	8	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	103	","	汤原	","	050402	","	8	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	104	","	抚远	","	050403	","	8	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	105	","	桦川	","	050404	","	8	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	106	","	桦南	","	050405	","	8	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	107	","	同江	","	050406	","	8	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	108	","	富锦	","	050407	","	8	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	109	","	绥化	","	050501	","	9	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	110	","	肇东	","	050502	","	9	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	111	","	安达	","050503	","	9	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	112	","	海伦	","	050504	","	9	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	113	","	明水	","	050505	","	9	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	114	","	望奎	","	050506	","	9	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	115	","	兰西	","	050507	","	9	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	116	","	青冈	","	050508	","	9	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	117	","	庆安	","	050509	","	9	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	118	","	绥棱	","	050510	","	9	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	119	","	黑河	","	050601	","	10	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	120	","	嫩江	","	050602	","	10	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	121	","	孙吴	","	050603	","	10	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	122	","	逊克	","	050604	","	10	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	123	","	五大连池	","	050605	","	10	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	124	","	北安	","	050606	","	10	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	125	","	大兴安岭	","	050701	","	11	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	126	","	塔河	","	050702	","	11	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	127	","	漠河	","	050703	","	11	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	128	","	呼玛	","	050704	","	11	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	129	","	呼中	","	050705	","	11	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	130	","	新林	","	050706	","	11	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	131	","	加格达奇	","	050708	","	11	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	132	","	伊春	","	050801	","	12	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	133	","	乌伊岭	","	050802	","	12	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	134	","	五营	","	050803	","	12	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	135	","	铁力	","	050804	","	12	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	136	","	嘉荫	","	050805	","	12	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	137	","	大庆	","	050901	","	13	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	138	","	林甸	","	050902	","	13	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	139	","	肇州	","	050903	","	13	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	140	","	肇源	","	050904	","	13	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	141	","	杜尔伯特	","	050905	","	13	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	142	","	七台河	","	051002	","	14	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	143	","	勃利	","	051003	","	14	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	144	","	鸡西	","	051101	","	15	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	145	","	虎林	","	051102	","	15	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	146	","	密山	","	051103	","	15	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	147	","	鸡东	","	051104	","	15	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	148	","	鹤岗	","	051201	","	16	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	149	","	绥滨	","	051202	","	16	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	150	","	萝北	","	051203	","	16	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	151	","	双鸭山	","	051301	","	17	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	152	","	集贤	","	051302	","	17	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	153	","	宝清	","	051303	","	17	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	154	","	饶河	","	051304	","	17	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	155	","	友谊	","	051305	","	17	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	156	","	长春	","	060101	","	18	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	157	","	农安	","	060102	","	18	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	158	","	德惠	","	060103	","	18	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	159	","	九台	","	060104	","	18	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	160	","	榆树	","	060105	","	18	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	161	","	双阳	","	060106	","	18	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	162	","	吉林	","	060201	","	19	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	163	","	舒兰	","	060202	","	19	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	164	","	永吉	","	060203	","	19	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	165	","	蛟河	","	060204	","	19	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	166	","	磐石	","	060205	","	19	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	167	","	桦甸	","	060206	","	19	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	168	","	延吉	","	060301	","	20	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	169	","	敦化	","	060302	","	20	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	170	","	安图	","	060303	","	20	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	171	","	汪清	","	060304	","	20	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	172	","	和龙	","	060305	","	20	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	173	","	龙井	","	060307	","	20	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	174	","	珲春	","	060308	","	20	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	175	","	图们	","	060309	","	20	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	176	","	四平	","	060401	","	21	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	177	","	双辽	","	060402	","	21	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	178	","	梨树	","	060403	","	21	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	179	","	公主岭	","	060404	","	21	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	180	","	伊通	","	060405	","	21	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	181	","	通化	","	060501	","	22	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	182	","	梅河口	","	060502	","	22	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	183	","	柳河	","	060503	","	22	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	184	","	辉南	","	060504	","	22	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	185	","	集安	","	060505	","	22	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	186	","	通化县	","	060506	","	22	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	187	","	白城	","	060601	","	23	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	188	","	洮南	","	060602	","	23	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	189	","	大安	","	060603	","	23	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	190	","	镇赉	","	060604	","	23	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	191	","	通榆	","	060605	","	23	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	192	","	辽源	","	060701	","	24	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	193	","	东丰	","	060702	","	24	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	194	","	东辽	","	060703	","	24	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	195	","	松原	","	060801	","	25	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	196	","	乾安	","	060802	","	25	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	197	","	前郭	","	060803	","	25	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	198	","	长岭	","	060804	","	25	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	199	","	扶余	","	060805	","	25	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	200	","	白山	","	060901	","	26	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	201	","	靖宇	","	060902	","	26	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	202	","	临江	","	060903	","	26	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	203	","	东岗	","	060904	","	26	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	204	","	长白	","	060905	","	26	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	205	","	抚松	","	060906	","	26	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	206	","	江源	","	060907	","	26	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	207	","	沈阳	","	070101	","	27	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	208	","	辽中	","	070103	","	27	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	209	","	康平	","	070104	","	27	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	210	","	法库	","	070105	","	27	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	211	","	新民	","	070106	","	27	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	212	","	大连	","	070201	","	28	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	213	","	瓦房店	","	070202	","	28	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	214	","	金州	","	070203	","	28	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	215	","	普兰店	","	070204	","	28	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	216	","	旅顺	","	070205	","	28	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	217	","	长海	","	070206	","	28	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	218	","	庄河	","	070207	","	28	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	219	","	鞍山	","	070301	","	29	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	220	","	台安	","	070302	","	29	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	221	","	岫岩	","	070303	","	29	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	222	","	海城	","	070304	","	29	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	223	","	抚顺	","	070401	","	30	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	224	","	新宾	","	070402	","	30	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	225	","	清原	","	070403	","	30	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	226	","	章党	","	070404	","	30	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	227	","	本溪	","	070501	","	31	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	228	","	本溪县	","	070502	","	31	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	229	","	桓仁	","	070504	","	31	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	230	","	丹东	","	070601	","	32	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	231	","	凤城	","	070602	","	32	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	232	","	宽甸	","	070603	","	32	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	233	","	东港	","	070604	","	32	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	234	","	锦州	","	070701	","	33	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	235	","	凌海	","	070702	","	33	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	236	","	义县	","	070704	","	33	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	237	","	黑山	","	070705	","	33	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	238	","	北镇	","	070706	","	33	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	239	","	营口	","	070801	","	34	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	240	","	大石桥	","	070802	","	34	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	241	","	盖州	","	070803	","	34	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	242	","	阜新	","	070901	","	35	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	243	","	彰武	","	070902	","	35	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	244	","	辽阳	","	071001	","	36	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	245	","	辽阳县	","	071002	","	36	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	246	","	灯塔	","	071003	","	36	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	247	","	弓长岭	","	071004	","	36	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	248	","	铁岭	","	071101	","	37	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	249	","	开原	","	071102	","	37	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	250	","	昌图	","	071103	","	37	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	251	","	西丰	","	071104	","	37	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	252	","	调兵山	","	071105	","	37	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	253	","	朝阳	","	071201	","	38	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	254	","	凌源	","	071203	","	38	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	255	","	喀左	","	071204	","	38	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	256	","	北票	","	071205	","	38	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	257	","	建平县	","	071207	","	38	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	258	","	盘锦	","	071301	","	39	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	259	","	大洼	","	071302	","	39	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	260	","	盘山	","	071303	","	39	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	261	","	葫芦岛	","	071401	","	40	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	262	","	建昌	","	071402	","	40	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	263	","	绥中	","	071403	","	40	"});
        db.execSQL("insert into County values (?,?,?,?)",new String[] {"	264	","	兴城	","	071404	","	40	"});



    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }
}
